# Databricks App Configuration
command: ['python', 'app.py']

# Static files configuration
static_files:
  - source_path: static
    url_path: /

env:
  - name: 'DATABRICKS_WAREHOUSE_ID'
    valueFrom: 'sql-warehouse'